### ISSUE TITLE
Dynamic form fields

### ISSUE THREAD

**Issue by Wenze** [mbertheau/jquery.django-formset#3] opened 2014-09-15 09:43 UTC
Hi Markus,

Just stumbled on this repository and from the documentation it sounds like a great project. I haven't tried to use it yet but I was wondering if the following would be possible (with some extra jquery/javascript):
- Create multiple "add another form" buttons, like: add open question, add multiple choice question
- Render form with fields specified for each button type
- Use a nested formset depending on the selected button

I've added a drawing to make it clear. Do you have an idea if something like this could work?

Also, when using jQuery to re-order the forms, will adding and deleting the forms still work correctly? Because the order of the forms is changed.
![example drawing question form](https://cloud.githubusercontent.com/assets/3382304/4269450/6e4d2d7e-3cbc-11e4-9b30-f5fe11e24c83.png)

**Comment by mbertheau** [comment] 2014-10-27 01:05
Hi Wenze,

at first, sorry for answering so late.

To address your questions:

For the multiple question types formset: Firstly, nested formsets like for the multiple choice question are supported out of the box - the tricky part here is to get the template with the empty forms correct. The rest depends on how the question forms are modeled in Django, and by extension how the forms should appear in the HTML. You can have A) one question form with all possible fields, and just the common fields appear by default. Then you have the two buttons, which both call `addForm`, and then apply a class or something similar to unhide the corresponding other question fields. On the other hand, if you have B) different forms for different question types and you interleave them, then you can have two (or more) formsets on the page, but you'd have to modify the JS to make sure that new questions appear in the right place.

You can have as many "add another form" buttons as you like, you just have to make sure that `addForm` is called when they're clicked. You can have different click handlers that do different things to the form once it was added, or they can add forms to different formsets.

`jquery.django-formset` has no support for ordering built-in. Internally it uses a list of forms with their DOM elements. The formset is oblivious to the order of the forms in the DOM. To support ordering in variant A), after changing the order of the forms as they appear on the page, you'd have to reflect that ordering change in the list of forms used by the plugin. If you are so inclined, you can also add a re-ordering API to the formset/form that moves the form as it appears on the page, and also modifies the list of forms. This API could be called from the reordering JS.

Variant B) is a bit harder to support, since you have to maintain one ordering over two or more different formsets.

I'll close this as it is not a bug in the software. Feel free to re-open if you have a follow-up question.

Thank you for your interest in this plugin :)

**Closed as completed by mbertheau** 2014-10-27 01:05 UTC
Labels: question
